name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest
#    runs-on: ubuntu-latest # Error: setup-msbuild can only be run on Windows runners
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup .NET
      uses: microsoft/setup-msbuild@v1.3
    - name: C# problem matcher
      run: |
        Invoke-WebRequest "https://raw.githubusercontent.com/actions/setup-dotnet/main/.github/csc.json" -OutFile "csc.json"
        echo "::add-matcher::csc.json"
#      uses: actions/setup-dotnet@v2
#      with:
#        dotnet-version: 5.0.x
#    - name: Restore dependencies
#      run: dotnet restore
    - name: Add Packages
      run: |
        dotnet restore
    - name: Build
#      run: make all # builds the Debug configuration
      run: |
        msbuild /property:Configuration=Release
        msbuild /property:Configuration=Debug
#      run: dotnet build --no-restore
    - name: Test
      run: |
          dotnet test --no-build --verbosity normal
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: EDSEditor
        path: EDSEditorGUI\bin\Release\
